name: Build and Tests on AArch64
on:
  pull_request:
  schedule:
    - cron:  '0 15 * * 0'

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        module: ["core", "metrics", "rules core metrics", "reporters core", "driver core"]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - uses: uraimo/run-on-arch-action@v2.0.7
        with:
          arch: aarch64
          distro: ubuntu20.04
          env: |
            test_module: ${{ matrix.module }}
          install: |
            apt-get update
            apt-get install -y curl git g++ python python3 cmake zlib1g-dev libncurses-dev
          run: |
            cd oclint-scripts && ./gh-actions test ${test_module}
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - uses: uraimo/run-on-arch-action@v2.0.7
        with:
          arch: aarch64
          distro: ubuntu20.04
          install: |
            apt-get update
            apt-get install -y curl git g++ python python3 cmake zlib1g-dev libncurses-dev
          run: |
            cd oclint-scripts && ./gh-actions build
