name: Build Using System LLVM
on:
  pull_request:
  schedule:
    - cron:  '0 15 * * 0'

jobs:
  build-on-linux:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, ubuntu-18.04, ubuntu-16.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 12
          sudo apt-get -y install libllvm12 llvm-12 llvm-12-dev llvm-12-runtime clang-12 clang-tools-12 libclang-common-12-dev libclang-12-dev libclang1-12
      - run: |
          cd oclint-scripts
          ./build -no-ninja -llvm-root=/usr/lib/llvm-12
          ./bundle -archive -llvm-root=/usr/lib/llvm-12
  build-on-mac:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - run: |
          sudo xcode-select -s /Applications/Xcode_12.5.app/Contents/Developer
          HOMEBREW_NO_AUTO_UPDATE=1 brew install llvm@12
      - run: |
          cd oclint-scripts
          ./build -no-ninja -llvm-root=/usr/local/opt/llvm\@12
          ./bundle -archive -llvm-root=/usr/local/opt/llvm\@12
