name: Tests
on: [push, pull_request]

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-10.15]
        include:
          - module: "core"
            deps: ""
          - module: "metrics"
            deps: ""
          - module: "rules"
            deps: "core metrics"
          - module: "reporters"
            deps: "core"
          - module: "driver"
            deps: "core"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - run: sudo pip install --upgrade cpp-coveralls;
        if:  matrix.os == 'ubuntu-20.04'
      - run: |
          sudo xcode-select -s /Applications/Xcode_12.2.app/Contents/Developer
          HOMEBREW_NO_AUTO_UPDATE=1 brew install pyenv;
          eval "$(pyenv init -)";
          pyenv install 3.8.2;
          pyenv global 3.8.2;
          pyenv rehash;
          pip install cpp-coveralls;
          pyenv rehash;
        if:  matrix.os == 'macos-10.15'
      - env:
          MODULE: ${{ matrix.module }}
          DEPS: ${{ matrix.deps }}
        run: cd oclint-scripts && ./gh-actions test $MODULE $DEPS && cd ..
      - env:
          MODULE: ${{ matrix.module }}
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: coveralls --include oclint-${MODULE}/ --exclude oclint-${MODULE}/test
        if:  matrix.os == 'ubuntu-20.04' && matrix.module != 'driver'
      - env:
          MODULE: ${{ matrix.module }}
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: coveralls --gcov ./build/llvm-install/bin/llvm-cov --gcov-options gcov --include oclint-${MODULE}/ --exclude oclint-${MODULE}/test
        if:  matrix.os == 'macos-10.15' && matrix.module != 'driver'
