name: Tests
on: [push, pull_request]

jobs:
  tests-on-linux:
    name: Tests on Linux
    strategy:
      fail-fast: false
      matrix:
        include:
          - module: "core"
            deps: ""
          - module: "metrics"
            deps: ""
          - module: "rules"
            deps: "core metrics"
          - module: "reporters"
            deps: "core"
          - module: "driver"
            deps: "core"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - env:
          MODULE: ${{ matrix.module }}
          DEPS: ${{ matrix.deps }}
        run: cd oclint-scripts && ./gh-actions test $MODULE $DEPS && cd ..
      - env:
          MODULE: ${{ matrix.module }}
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: |
          sudo pip install --upgrade cpp-coveralls
          coveralls --include oclint-${MODULE}/ --exclude oclint-${MODULE}/test
        if:  matrix.module != 'driver'
  tests-on-mac:
    name: Tests on macOS
    strategy:
      fail-fast: false
      matrix:
        include:
          - module: "core"
            deps: ""
          - module: "metrics"
            deps: ""
          - module: "rules"
            deps: "core metrics"
          - module: "reporters"
            deps: "core"
          - module: "driver"
            deps: "core"
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v1
      - run: sudo xcode-select -s /Applications/Xcode_12.2.app/Contents/Developer
      - env:
          MODULE: ${{ matrix.module }}
          DEPS: ${{ matrix.deps }}
        run: cd oclint-scripts && ./gh-actions test $MODULE $DEPS && cd ..
      - env:
          MODULE: ${{ matrix.module }}
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: |
          HOMEBREW_NO_AUTO_UPDATE=1 brew install pyenv
          eval "$(pyenv init -)"
          pyenv install 3.8.2
          pyenv global 3.8.2
          pyenv rehash
          pip install cpp-coveralls
          pyenv rehash
          coveralls --gcov $(pwd)/build/llvm-install/bin/llvm-cov --gcov-options gcov --include oclint-${MODULE}/ --exclude oclint-${MODULE}/test
        if:  matrix.module != 'driver'
